@startuml
!theme toy
title Architecture – Netnet 
actor Client

cloud "Internet" as Internet

node "Docker Host" {

  package "Public Network" #LightBlue {
    component "Caddy\n(public)" as Caddy
    component "Tailscale\n(VPN)" as TS #Pink
  }

  package "Internal Network" #LightGreen {
    component "Front-end" as Front
    component "Back-end" as API
    database "MongoDB" as DB
  }
}

Client --> Internet
Internet --> Caddy : HTTP
Caddy --> Front : /home
Caddy --> API 

API --> DB

Client --> TS : Accès privé (VPN)
TS --> Caddy

@enduml